camera_serial_no: "4103241612"
nb_buffers: 8

trigger_mode: "TRIGGER_HI_LO"
trigger_delay: 15
color_mode: "MONO8"
hdr_mode: true
image_width: 0
image_height: 0
offset_x: 0
offset_y: 0

pixel_clock: 10
frame_rate: 10.0
exposure_time: 15
gain: 100
